namespace FreeroamShared
{
	public enum PhoneAppIcon
	{
		APP_CAMERA = 1,
		APP_CHAT,
		APP_EMPTY,
		APP_MESSAGING = 4,
		APP_CONTACTS,
		APP_INTERNET,
		APP_CONTACTS_PLUS = 11,
		APP_TASKS,
		APP_GROUP = 14,
		APP_SETTINGS = 24,
		APP_WARNING = 27,
		APP_GAMES = 35,
		APP_RIGHT_ARROW = 38,
		APP_TASKS_2,
		APP_TARGET,
		APP_TRACKIFY = 42,
		APP_CLOUD,
		APP_BROADCAST = 49,
		APP_VLSI = 54,
		APP_BENNYS = 56,
		APP_SECUROSERV,
		APP_COORDS,
		APP_RSS
	}

	public enum PhoneSelectSlot
	{
		SLOT_LEFT = 1,
		SLOT_MIDDLE,
		SLOT_RIGHT
	}

	public enum PhoneSelectIcon
	{
		ICON_BLANK = 1,
		ICON_SELECT,
		ICON_PAGES,
		ICON_BACK,
		ICON_CALL,
		ICON_HANGUP,
		ICON_HANGUP_HUMAN,
		ICON_WEEK,
		ICON_KEYPAD,
		ICON_OPEN,
		ICON_REPLY,
		ICON_DELETE,
		ICON_YES,
		ICON_NO,
		ICON_SORT,
		ICON_WEBSITE,
		ICON_POLICE,
		ICON_AMBULANCE,
		ICON_FIRE,
		ICON_PAGES2,

	}
}
